add editline and arena per iteration

diff --git a/impls/odin/Makefile b/impls/odin/Makefile
--- a/impls/odin/Makefile
+++ b/impls/odin/Makefile
@@ -1,6 +1,16 @@
 STEPS = step0_repl
+BINDGEN ?= bindgen
 
 all: $(STEPS)
+
+bindings:
+	@$(BINDGEN) vendor/editline || { \
+		echo ""; \
+		echo "Could not run '$(BINDGEN)'."; \
+		echo "Build/install odin-c-bindgen, or run:"; \
+		echo "  make -C impls/odin BINDGEN=/path/to/bindgen.bin bindings"; \
+		exit 127; \
+	}
 
 dist: mal
 
@@ -12,3 +22,5 @@ $(STEPS): %: %.odin
 
 clean:
 	rm -f $(STEPS) mal
+
+.PHONY: all clean bindings
